# Generated by Django 5.2.5 on 2025-08-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='aapm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='comentarios',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='curso_turma',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='futebol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='nome_time',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='quant_time',
            field=models.PositiveIntegerField(default=' '),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='telefone',
            field=models.PositiveIntegerField(default=' '),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='tenis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='volei',
            field=models.BooleanField(default=False),
        ),
    ]
