# Generated by Django 5.2.5 on 2025-08-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='curso_turma',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
