# Generated by Django 5.2.5 on 2025-08-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0002_inscrito_curso_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='nome_time',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
