# Generated by Django 5.2.5 on 2025-08-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0002_inscrito_aapm_inscrito_comentarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='quant_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='telefone',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
