# Generated by Django 5.2.5 on 2025-08-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0003_inscrito_nome_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
    ]
