# Generated by Django 5.2.5 on 2025-08-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0004_inscrito_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='volei',
            field=models.BooleanField(default=False),
        ),
    ]
