# Generated by Django 5.2.5 on 2025-08-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0005_inscrito_volei'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='aapm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='futebol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='tenis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='time',
            field=models.BooleanField(default=False),
        ),
    ]
