# Generated by Django 5.2.5 on 2025-08-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0005_alter_inscrito_quant_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='quant_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
