# Generated by Django 5.2.5 on 2025-08-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0006_inscrito_aapm_inscrito_futebol_inscrito_tenis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='comentarios',
            field=models.TextField(default=' '),
        ),
    ]
