# Generated by Django 5.2.5 on 2025-08-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0007_inscrito_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='telefone',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
