# Generated by Django 5.2.5 on 2025-08-13 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0008_remove_inscrito_quant_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscrito',
            name='aapm',
        ),
        migrations.RemoveField(
            model_name='inscrito',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='inscrito',
            name='curso_turma',
        ),
        migrations.RemoveField(
            model_name='inscrito',
            name='email',
        ),
        migrations.RemoveField(
            model_name='inscrito',
            name='futebol',
        ),
        migrations.RemoveField(
            model_name='inscrito',
            name='nome_time',
        ),
        migrations.RemoveField(
            model_name='inscrito',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='inscrito',
            name='tenis',
        ),
        migrations.RemoveField(
            model_name='inscrito',
            name='time',
        ),
        migrations.RemoveField(
            model_name='inscrito',
            name='volei',
        ),
    ]
