# Generated by Django 5.2.5 on 2025-08-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0008_inscrito_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='quant_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
