# Generated by Django 5.2.5 on 2025-08-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0009_inscrito_quant_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscrito',
            name='quant_time',
        ),
    ]
